name: Build, Test, Release, Deploy

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build, Test and Release Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/invoicify.jar
          asset_name: invoicify.jar
          tag: 'Releases'
          overwrite: true
          body: "invoicify-v1.jar"

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    name: Docker Build, Tag, Push
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ghazanfar9131/java-pundits-invoicify
          tag_with_sha: true

  deploy:
    runs-on: ubuntu-latest
    name: Deploying to Heroku
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Heroku Docker Container Deploy
        uses: Techmmunity/docker-heroku-deploy@v1.0.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: ''

